### ISSUE TITLE
The mail job is failing

### ISSUE THREAD

**Issue by stvnrlly** [18F/C2#1666]
Something's up with ActionMailer that's causing the job to fail. 

Here's the error message: 

```
Address family not supported by protocol - socket(2) for nil port 25 /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:542:in `initialize' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:542:in `open' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/timeout.rb:101:in `timeout' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/net/smtp.rb:521:in `start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/mail-2.7.0/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:2160:in `do_delivery' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:260:in `block in deliver' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:543:in `block in deliver_mail' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:541:in `deliver_mail' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/mail-2.7.0/lib/mail/message.rb:260:in `deliver' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/roadie-rails-1.1.0/lib/roadie/rails/inline_on_delivery.rb:11:in `deliver' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/delivery_job.rb:10:in `perform' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:32:in `block in perform_now' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/active_job.rb:46:in `perform' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/active_job.rb:20:in `block (3 levels) in <top (required)>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/i18n-0.9.3/lib/i18n.rb:268:in `with_locale' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `block in tag_logger' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `tag_logger' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:31:in `perform_now' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:21:in `execute' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:34:in `perform' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:100:in `block in invoke_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/backend/base.rb:97:in `invoke_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:129:in `block in invoke_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:128:in `invoke_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block (2 levels) in run' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/timeout.rb:101:in `timeout' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:224:in `block in run' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/benchmark.rb:308:in `realtime' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:223:in `run' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `block in reserve_and_run_one_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:300:in `reserve_and_run_one_job' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:207:in `block in work_off' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `times' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:206:in `work_off' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:169:in `block (4 levels) in start' /home/vcap/deps/0/ruby/lib/ruby/2.3.0/benchmark.rb:308:in `realtime' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:168:in `block (3 levels) in start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:167:in `block (2 levels) in start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `loop' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:166:in `block in start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:61:in `block in initialize' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:79:in `block in add' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:66:in `execute' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/lifecycle.rb:40:in `run_callbacks' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/worker.rb:165:in `start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:131:in `run' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:119:in `block in run_process' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:265:in `block in start_proc' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:274:in `start_proc' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons/application.rb:295:in `start' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons/controller.rb:59:in `run' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons.rb:193:in `block in run_proc' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/daemons-1.2.3/lib/daemons.rb:192:in `run_proc' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:117:in `run_process' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:98:in `block in daemonize' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:96:in `times' /home/vcap/deps/0/vendor_bundle/ruby/2.3.0/gems/delayed_job-4.1.1/lib/delayed/command.rb:96:in `daemonize' bin/delayed_job:5:in `<main>'
```

**Comment by amoose** [comment]
The application configuration for SES was not updated and deployed since moving off of Mandrill. Therefore, the SMTP lib was attempting a socket connection to the SMTP server (as expected). @stvnrlly went ahead and updated the credentials and restaged `c2-prod-worker`. The worker is now attempting to send via TCP but SES is responding with `535 Authentication Credentials Invalid`. I've requested new credentials from #infrastructure and will update and restage the worker once we have them. 

Thanks @stvnrlly 

Blocked by:
https://github.com/18F/Infrastructure/issues/884

**Comment by amoose** [comment]
#Infra promptly delivered SES credentials yesterday and I made the switch to API-delivered mail in PR #1668. Tested with @stvnrlly in dev and everything looks good. Steven will deploy the update on Monday.

**Comment by amoose** [comment]
Emails are flowing again! https://gsa-tts.slack.com/archives/C0E1APHGU/p1525098395000466
